name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the project
        run: echo "test" # Commande pour construire votre projet

  test:
    runs-on: ubuntu-latest
    needs: build  # Exécuter après le job 'build'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: echo "test"

      - name: Run tests
        run: echo "test"
