name: Build and Test

on:
  pull_request:
    types: [opened, synchronize,push]
permissions:
  contents: read
  packages: read
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the project
        run: echo "test" # Commande pour construire votre projet
      - name: Generate summary
        run: |
          echo "## Build Success" >> $GITHUB_STEP_SUMMARY
          echo "The project was successfully built!" >> $GITHUB_STEP_SUMMARY
          echo "### Attestation Created" >> $GITHUB_STEP_SUMMARY
          echo "[artifact@sha256:832f9c02ed57de5771f84cd540ae2b89c57b3aeda89a5ed92580cd372810c7e9](link_to_artifact)" >> $GITHUB_STEP_SUMMARY
  test:
    runs-on: ubuntu-latest
    needs: build  # Exécuter après le job 'build'

    steps:
      # Checkout du dépôt
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-caddy-image .

      # Démarrer un conteneur Caddy
      - name: Run Caddy container
        run: docker run -d -p 80:80 my-caddy-image

      # Vérifier que Caddy est bien installé
      - name: Check Caddy version
        run: |
          CADDY_VERSION=$(docker run --rm my-caddy-image caddy version)
          if [[ "$CADDY_VERSION" == v2.8.4* ]]; then
            echo "Caddy version is correct: $CADDY_VERSION"
          else
            echo "Unexpected Caddy version: $CADDY_VERSION"
            exit 1
          fi
      - name: Test Caddy HTTP response
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:80)
          if [ "$STATUS_CODE" != "200" ]; then
            echo "Unexpected status code: $STATUS_CODE"
            exit 1
          else
            echo "Caddy is running correctly with status code: $STATUS_CODE"
          fi
      - name: Generate summary
        run: |
          echo "## Build Success" >> $GITHUB_STEP_SUMMARY
          echo "The project was successfully built!" >> $GITHUB_STEP_SUMMARY
          echo "### Attestation Created" >> $GITHUB_STEP_SUMMARY
          echo "[artifact@sha256:832f9c02ed57de5771f84cd540ae2b89c57b3aeda89a5ed92580cd372810c7e9](link_to_artifact)" >> $GITHUB_STEP_SUMMARY